// <auto-generated />
using System;
using InsulinAndCoffee.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsulinAndCoffee.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625190306_RenameKnownMealsToDeliveryMeals")]
    partial class RenameKnownMealsToDeliveryMeals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "meal_type", new[] { "breakfast", "lunch", "dinner", "snack" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "reading_type", new[] { "before_meal", "after_meal", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "result_rating", new[] { "perfect", "good", "high_glucose", "low_glucose", "unknown" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.DeliveryMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Carbs")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LastPreMealGlucose")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("PortionDescription")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<int>("ResultRating")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UsualInsulinUnits")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsFavorite");

                    b.HasIndex("UserId", "UsageCount");

                    b.HasIndex("UserId", "PlaceName", "DishName");

                    b.ToTable("DeliveryMeals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            Carbs = 95m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DishName = "Philadelphia Set",
                            IsFavorite = true,
                            Notes = "Reliable repeat order.",
                            PlaceName = "Sushi Master",
                            PortionDescription = "standard set",
                            ResultRating = 2,
                            Tags = "sushi, delivery, dinner",
                            UsageCount = 0,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsualInsulinUnits = 7m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            Carbs = 67m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DishName = "Cottage Cheese Casserole",
                            IsFavorite = true,
                            Notes = "Good with coffee.",
                            PlaceName = "Local Cafe",
                            PortionDescription = "one slice",
                            ResultRating = 2,
                            Tags = "cafe, dessert, breakfast",
                            UsageCount = 0,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsualInsulinUnits = 6m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            Carbs = 80m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DishName = "Shawarma",
                            IsFavorite = false,
                            Notes = "Check glucose response next time.",
                            PlaceName = "Delivery",
                            PortionDescription = "standard",
                            ResultRating = 5,
                            Tags = "delivery, lunch",
                            UsageCount = 0,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsualInsulinUnits = 8m
                        });
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.DiabetesSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CarbRatio")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("CorrectionFactor")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("InsulinDurationHours")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<decimal>("TargetGlucose")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DiabetesSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CarbRatio = 10m,
                            CorrectionFactor = 3m,
                            InsulinDurationHours = 4m,
                            TargetGlucose = 6.5m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CaloriesPer100g")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("CarbsPer100g")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FatPer100g")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal>("ProteinPer100g")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            CaloriesPer100g = 0m,
                            CarbsPer100g = 25m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FatPer100g = 0m,
                            IsFavorite = true,
                            Name = "Philadelphia Roll",
                            ProteinPer100g = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            CaloriesPer100g = 0m,
                            CarbsPer100g = 28m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FatPer100g = 0m,
                            IsFavorite = false,
                            Name = "Sushi Rice",
                            ProteinPer100g = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            CaloriesPer100g = 0m,
                            CarbsPer100g = 45m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FatPer100g = 0m,
                            IsFavorite = true,
                            Name = "Bread",
                            ProteinPer100g = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            CaloriesPer100g = 0m,
                            CarbsPer100g = 1m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FatPer100g = 0m,
                            IsFavorite = false,
                            Name = "Butter",
                            ProteinPer100g = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            CaloriesPer100g = 0m,
                            CarbsPer100g = 27m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FatPer100g = 0m,
                            IsFavorite = true,
                            Name = "Cottage Cheese Casserole",
                            ProteinPer100g = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333306"),
                            CaloriesPer100g = 0m,
                            CarbsPer100g = 6m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FatPer100g = 0m,
                            IsFavorite = true,
                            Name = "Borscht",
                            ProteinPer100g = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333307"),
                            CaloriesPer100g = 0m,
                            CarbsPer100g = 8m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FatPer100g = 0m,
                            IsFavorite = false,
                            Name = "Chicken Cutlet",
                            ProteinPer100g = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333308"),
                            CaloriesPer100g = 0m,
                            CarbsPer100g = 5m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FatPer100g = 0m,
                            IsFavorite = true,
                            Name = "Latte",
                            ProteinPer100g = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333309"),
                            CaloriesPer100g = 0m,
                            CarbsPer100g = 55m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FatPer100g = 0m,
                            IsFavorite = true,
                            Name = "Chocolate",
                            ProteinPer100g = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.GlucoseReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("ReadingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReadingType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("UserId", "ReadingTime");

                    b.ToTable("GlucoseReadings");
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConfirmedBolus")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MealTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("PreMealGlucose")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("SuggestedBolus")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("TotalCarbs")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MealTime");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CalculatedCarbs")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("CarbsPer100gSnapshot")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("FoodNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightGrams")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("MealItems");
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "aleksandra@example.com",
                            Name = "Aleksandra"
                        });
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.DeliveryMeal", b =>
                {
                    b.HasOne("InsulinAndCoffee.Domain.Entities.User", "User")
                        .WithMany("DeliveryMeals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.DiabetesSettings", b =>
                {
                    b.HasOne("InsulinAndCoffee.Domain.Entities.User", "User")
                        .WithOne("DiabetesSettings")
                        .HasForeignKey("InsulinAndCoffee.Domain.Entities.DiabetesSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.FoodItem", b =>
                {
                    b.HasOne("InsulinAndCoffee.Domain.Entities.User", "User")
                        .WithMany("FoodItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.GlucoseReading", b =>
                {
                    b.HasOne("InsulinAndCoffee.Domain.Entities.Meal", "Meal")
                        .WithMany("GlucoseReadings")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsulinAndCoffee.Domain.Entities.User", "User")
                        .WithMany("GlucoseReadings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.Meal", b =>
                {
                    b.HasOne("InsulinAndCoffee.Domain.Entities.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.MealItem", b =>
                {
                    b.HasOne("InsulinAndCoffee.Domain.Entities.Meal", "Meal")
                        .WithMany("Items")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.Meal", b =>
                {
                    b.Navigation("GlucoseReadings");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("InsulinAndCoffee.Domain.Entities.User", b =>
                {
                    b.Navigation("DeliveryMeals");

                    b.Navigation("DiabetesSettings");

                    b.Navigation("FoodItems");

                    b.Navigation("GlucoseReadings");

                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
